spring:
  kafka:
    bootstrap-servers:  localhost:9092
    consumer:
      auto-offset-reset: earliest
      group-id: boot
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.letuslearn.kafkapoc.kafka.serialization.AvroDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.letuslearn.kafkapoc.kafka.serialization.AvroSerializer

kafka:
  topic:
    boot: avrotp12.t
  bootstrap-servers: localhost:9092
